services:
  db:
    image: postgres:15
    container_name: data_base
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file: # Файл с переменными окружения
      - .env
    environment:
      POSTGRES_DB: library_base
    ports:
      - 5432:5432

  app:
    image: app
    restart: always
    build:
      context: .
    container_name: app

    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000

volumes:
  postgresdata:



